apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-pythosudo co
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: ghassent/testdocker:v1
        #imagePullPolicy: Never
        ports:
        - containerPort: 5000